title: My Research | www.whing.cn
url: "http://whing.cn/research"
baseurl: "/research"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/vic9527"
footer_text: "Written by Vic"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about/"
 - name: "Resume"
   link: "/resume/"
 - name: "Blog"
   link: "/blog/"
